### ISSUE TITLE
Migrate to ESLint plugin.

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-suave#113]
http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

**Comment by hzoo** [comment]
Let us know how we can help

**Comment by raido** [comment]
https://github.com/jonathanKingston/ember-cli-eslint

Aren't this and the repo above now slowly moving in  same direction? In the end both will be using ESLint.

**Comment by rwjblue** [comment]
@raido - No, these projects are not at odds. ember-cli-eslint is providing the engine to run eslint rules within ember-cli, this project aims to provide a set of **suave** rules for your project.  Either way, ember-suave requires an engine to run the rules in (we use broccoli-jscs to run JSCS rules today and will use ember-cli-eslint to run rules in the future).

**Comment by raido** [comment]
@rwjblue: Got it :)

**Comment by alexlafroscia** [comment]
@rwjblue This is something I'd be interested in helping with, now that `ember-cli-eslint` is maturing.  How would you want to see this happen?  I'd imagine you would install `ember-cli-eslint` and `ember-suave` and it would "just work" from there... Is that your goal?

**Comment by brzpegasus** [comment]
So, I'm not sure that it makes sense to turn this repo into an ESLint plugin. Don't they have to be standalone packages named `eslint-plugin-*`?

I'm leaning towards this:

* Have a separate repo, called `eslint-plugin-ember-suave` or something. This would host all the custom rules and desired config.
* This repo could then be its own Ember CLI addon that works in conjunction with `ember-cli-eslint`, by:
  * `npm install`ing the `eslint-plugin-ember-suave` plugin
  * updating the project's `.eslintrc.js` and `tests/.eslintrc.js` files that `ember-cli-eslint` generates to use the plugin and extend from the plugin's config, something like:

```js
module.exports = {
  plugins: ['ember-suave'],
  extends: [
    './node_modules/ember-cli-eslint/coding-standard/ember-application.js',
    'plugin:ember-suave/recommended'
  ],
  rules: {
    // This is where users can override ember-suave rules
  }
};
```

**Comment by hzoo** [comment]
Yeah the equivalent of a jscs preset is a "eslint config" with the namespace `eslint-config-` which exports a eslintrc basically (I thought `eslint-preset-` works and it does but the shorthand way of using it doesn't).

**Comment by alexlafroscia** [comment]
For anyone curious, I've started a new repo that's porting over the rules one-for-one into ESLint.

https://github.com/alexlafroscia/eslint-plugin-ember-suave

Once the rules are equivalent, I'm happy to transfer the repo over to Dockyard.

**Comment by alexlafroscia** [comment]
My repo (linked above) has the four custom rules that this repo contains, with the same test cases, all passing.  My test infrastructure isn't quite as robust as what you use here, but ESLint provides a setup for testing rules so I just stuck with the defaults for now.  I'm thinking about ways to have the tests in ESLint run the same was as these, where you can just add a `.js` file to the right folder and it will be tested as valid/invalid automatically.

I do have a further question about the tests, though; why are there tests for so many of the built-in rules?  Is that something that you want the new ESLint package to also do?  It is just to show what the rules will pass and fail on?  ESLint provides pretty clear docs for their rules on their website, so if that's the reason, maybe having tests run for all of them can be avoided?

I think the next task is to port [`jscs-ember-deprecations`](https://github.com/minichate/jscs-ember-deprecations) over to ESLint as well, if that's something that should still be part of `ember-suave`.

**Comment by rwjblue** [comment]
> why are there tests for so many of the built-in rules? 

Many of them were not always built-in, we created them then the JSCS team pulled them into the upstream repo.

**Comment by brzpegasus** [comment]
Also, the tests were meant to ensure that `ember-suave` had the correct rules enabled or configured per DockYard's styleguide. I think the way you have set up the tests in the plugin repo itself should be fine though.

**Comment by brzpegasus** [comment]
> I think the next task is to port jscs-ember-deprecations over to ESLint as well, if that's something that should still be part of ember-suave.

I have been wanting to drop support for it, given exactly what you said: it hasn't been maintained.

Thank you so much for working on this issue by the way! I will take a look at the plugin repo you created and create an `eslint` branch on `ember-suave` that integrates it.

**Comment by alexlafroscia** [comment]
@rwjblue I see, that makes sense.

@brzpegasus sure thing; I love Suave and ESLint so this was something I've been wanting to do for a while, even before JSCS and ESLint got pulled together.  Plus it's been a great opportunity to learn more about writing ESLint rules, which I've never really done.

**Comment by alexlafroscia** [comment]
Just figured I would drop this link in here; I think you'll want to provide a [shareable config](http://eslint.org/docs/developer-guide/shareable-configs) for Ember Suave with all of your favorite rules turned on.  It seems really verbose to have it in a separate repo than the rules, but the ESLint convention seems to be custom rules in an `eslint-plugin-foo` repo and custom configs in an `eslint-config-foo` repo.

**Comment by alexlafroscia** [comment]
Just as an update: I added a "recommended" config, just like @brzpegasus described, at `plugin:ember-suave/recommended`.  I don't know if it's a perfect port, but I started converting the rules from JSCS to ESLint by hand and realized it was going to take too long, so I just used [Polyjuice](https://www.npmjs.com/package/polyjuice) to do it.  It doesn't include any of the `ember-deprecations` rules, but should, in theory, cover all of the ESLint default and `ember-suave` custom rules.

**Comment by brzpegasus** [comment]
@alexlafroscia I'm experimenting with an `eslint-config-ember-suave` that sets up all the config for the built in rules, as well as the custom rules from your plugin. The idea is that the ember-suave config would bring together all the rules from various places: eslint (defaults), the custom rules from the suave plugin, and possibly rules from other third-party plugins, as applicable in the future. As such, I think it'd be preferable to leave out the config from the suave plugin you created.

I've also created a local branch that has ember-suave install the blueprint from ember-cli-eslint, so that it can then update it with the suave config.

I'm just running into some npm dependency issues at the moment because the plugin has to be a top-level dependency, not just a dependency of `eslint-config-ember-suave` (must be a peer dependency, essentially). I could also drop the config repo altogether and just have ember-suave hosts the config file but then users would have to reference the config using `require.resolve('ember-suave/config/index.js')` or something. I suppose that wouldn't be so bad either.

Still a WIP but that's the update.

**Comment by brzpegasus** [comment]
@alexlafroscia Feel free to post new comments rather than editing your previous posts by the way. Otherwise, I don't get notified when you post an edit.

**Comment by alexlafroscia** [comment]
Sorry about that, just didn't want to be too noisy here. 

I'm curious about the difference between having an `eslint-config-ember-suave` repo and having a config within the plugin, like I have set up now. I personally feel like having three repos for Suave is a lot; is there a benefit to splitting the config out into its own repo?

**Comment by brzpegasus** [comment]
> I'm curious about the difference between having an eslint-config-ember-suave repo and having a config within the plugin

Right now, the plugin defines a set of custom rules, but the config that lives in that repo isn't just for those custom rules. It's for everything that we want to support. Let's say that in the future, we would like the config to enable custom rules that are defined in other plugins, I don't think we should have `eslint-plugin-ember-suave` pull in other plugins. I'd rather have the repo where the config is defined be the aggregator. It would pull in any custom rules that it needs from various sources, e.g.:

```js
  plugins: [
    'ember-suave', // for custom rules not defined anywhere else
    'foo-plugin',
    'bar-plugin'
  ]
```

I agree that having 3 different repos seems excessive. We could technically get away with just having an `eslint-config-ember-suave` for the "preset", and `eslint-plugin-ember-suave` for the custom rules, and they could be used by any ESLint-enabled tool even outside of the Ember addon realm (see #126). The only benefit of having the `ember-suave` addon at this point is so that it would do the `npm install` and ESLint configuration steps for you instead of you manually setting up `ember-cli-eslint`, then `eslint-config-ember-suave`, then update `.eslintrc.js` in both the project root and `tests` folder.

The alternative that I mentioned, which would reduce the number of repos involved, is to simply host the config file within the `ember-suave` addon itself. We'd still keep `eslint-plugin-ember-suave` around for when we need to define custom rules. But the config file in that case would look more like this:

```js
  plugins: [
    require.resolve('ember-suave/lib/config/index.js'),
    'foo-plugin',
    'bar-plugin'
  ]
```

Thoughts?

**Comment by alexlafroscia** [comment]
> I don't think we should have `eslint-plugin-ember-suave` pull in other plugins

Yeah, I suppose that does make sense.  At the same time, I'm not sure there's a reason _not_ to have it pull in or configure others, especially when it's pretty easy to turn off any of that behavior that you're not interested in.

If the config is going to live outside of the plugin, then I think it should have it's own config repo that matches the pattern of the ESLint community.  Better to go with the convention, and I like the idea of other projects being able to use the configuration if they want to.

I think the idea of the `ember-suave` addon simply running some installation steps for the other packages a little strange.  Assuming the user already is using `ember-cli-eslint`, they'll likely already have `.eslintrc.js` files in place.  I feel like it would be just as easy to have people just install `ember-cli-eslint` and add the one `plugin:ember-suave/recommended` to their configuration; that's all they need to do.

**Comment by brzpegasus** [comment]
@alexlafroscia I'm going to stick to my original suggestion of having the `recommended` config inside `eslint-plugin-ember-suave` (basically what you ended up implementing). I agree it does simplify things. I had second thoughts for a while, so I consulted the [experts](https://groups.google.com/forum/#!topic/eslint/WipsFT9vnAA), who confirmed that for the use case of sharing configs across projects within a company, hosting the entire config within the plugin is acceptable. That's essentially what `ember-suave` set out to be: a way to share config across Ember projects at DockYard. Even if others within the Ember community can benefit from it, it is easy enough to override or extend the config within their own projects.

Progress has been slow on my part so far (can be challenging with a 2-month old to take care of at the same time) but I really want to get this over the finish line sooner rather than later. I might try to recruit other DYers to complete any missing rules as needed as well, since we'll want to use it on our next projects.

> I'm happy to transfer the repo over to Dockyard

This would be greatly appreciated. We'll certainly make sure to give you credit and we'll be happy to continue accepting contributions from you!

**Comment by alexlafroscia** [comment]
> We'll certainly make sure to give you credit and we'll be happy to continue accepting contributions from you!

Sounds good to me!  I'll set up the transfer now.  Who should I transfer the NPM package to?

**Comment by brzpegasus** [comment]
Can you transfer to my GH account, then I can transfer to DockYard?

For NPM, it can go to `edeblois`.

**Comment by brzpegasus** [comment]
> Maybe we can work together on coming up with a master list of what's missing

👍

**Comment by alexlafroscia** [comment]
Alright, I initiated the transfer of the Github repo to you, and added you as an owner on NPM and removed myself (since I figured you don't want me to retain publishing access on NPM).

**Comment by rwwagner90** [comment]
What can I do to help you guys with this effort?

**Comment by alexlafroscia** [comment]
@rwwagner90 [this issue](https://github.com/DockYard/eslint-plugin-ember-suave/issues/2) has a list of rules that existed in the JSCS version but do not (as far as I can tell) have an existing, built-in ESLint equivalent.  One of the major tasks left at this point is going through the ones that are left and either finding an ESLint rule that can be configured to cover it or implementing the rule ourselves.  Finding an existing third-party plugin might also be an appropriate solution but you'd have to talk to @brzpegasus about that, we might want to just keep the rules limited to built-ins or ones in that repo.

**Comment by rwwagner90** [comment]
I believe we have ported everything to ESLint, have we not @alexlafroscia @brzpegasus?

**Comment by alexlafroscia** [comment]
As far as I know, yes. Only things that come to mind are dropping `babel-eslint` and that generator thing. IMO the generator spacing issue is a non-blocker on a switch but, since this is really the Dockyard style guide, it's their call.

**Comment by alexlafroscia** [comment]
I've been using the ESLint version across a few apps and addons (like Ember AJAX) and it's been great.

**Comment by brzpegasus** [comment]
The generator styling is not a blocker by any means. In fact, if the eslint team does not think it is worth supporting the config, then it is probably worth revisiting our stance on it rather than creating a custom rule for a style that does not reflect widespread usage.

The repo can be used as it currently stands. I just need to remove the parser config (defaulting to Espree) and update documentation in light of some recent changes in `ember-cli-eslint` but nothing that should hold up the switch.

FWIW, I return to work next week from my extended leave, so there should be more activity from me in the near future.

**Comment by hzoo** [comment]
btw: https://github.com/eslint/eslint/issues/6053 will cover array/object destructuring as part of the JSCS Compatibility Milestone

**Comment by brzpegasus** [comment]
The plugin now exists as [eslint-plugin-ember-suave](https://github.com/DockYard/eslint-plugin-ember-suave).
