### ISSUE TITLE
disallowDirectPropertyAccess in conflict with blueprints

### ISSUE THREAD

**Issue by Suven** [DockYard/ember-suave#136]
Hey,

In edb98f6 disallowDirectPropertyAccess was changed to true for Ember.

As of Ember 2.7, the [blueprints are generating the opposite](http://emberjs.com/blog/2016/07/25/ember-data-2-7-released.html#toc_blueprint-changes)..

Personally I don't like the Constant-Handling as it might also introduce nameconflicts just for saving a few symbols, but that shouldn't matter. What should matter is that this introduces a split to what another part of the ember-community suggests.

**Comment by brzpegasus** [comment]
The blueprint change suggests moving away from the more granular `Model`, `attr`, etc. module imports because it requires that developers remember the actual module paths, which are not always intuitive.

The `disallowDirectPropertyAccess` rule isn't forcing you to use those modules. It just discourages accessing properties off of `DS` directly. Instead, you would import `DS` from `ember-data`, then use object destructuring:

```js
import DS from 'ember-data';

const { Model, attr } = DS;
```

Note that the same applies to destructuring things from `Ember`, even though the blueprints have never made it the default.
