### ISSUE TITLE
Should ember-suave be checking Ember-CLI generated files

### ISSUE THREAD

**Issue by danmcclain** [dockyard/ember-suave#25]
Ember-suave is correctly flagging issues with Ember-CLI generated files, but should it be? The files will continually have to be modified when ember-cli generates new ones. The other fix is to fix the generated files to pass the suaveness tests

**Comment by brzpegasus** [comment]
The problem is that the files that Ember CLI generates are also likely to be modified by users (some more likely than others). Let's take `router.js` as an example. Ideally, new code that you add to the file should be linted for style issues. But unless you're ok having mixed styles in the same file and having the part of the code that was generated explicitly ignored (e.g. via `/* jscs:disable */` comments or something), it may make more sense at that point to check the entire file.

If there are generated files you know you won't be modifying and don't care to run them through the linter, you could list them out in your own `.jscsrc` file with the `excludeFiles` option:

```json
{
  "excludeFiles": ["files/to/ignore/*.js"]
}
```

I hesitate to add that exclusion as part of the default addon config though, as it would mean that `ember-suave` now needs to be concerned with what files are generated by Ember CLI (and also keep that list updated as the blueprint changes).

**Comment by rwjblue** [comment]
I agree, we shouldn't modify our style requirements for older choices by ember-cli. Rather we should update ember-cli to pass our style tests....

**Comment by brzpegasus** [comment]
@danmcclain You probably noticed but Ember CLI >= 1.13.9 ships with blueprints that are ember-suave friendly.

**Comment by rwjblue** [comment]
:tada: !

**Comment by danmcclain** [comment]
🎉

**Comment by SmileyJames** [comment]
I am currently using ember-cli version 1.13.15
I get errors from the generated code, below is an example.
```
not ok 17 PhantomJS 2.1 - JSCS - helpers: helpers/module-for-acceptance.js should pass jscs
    ---
        actual: >
            false
        expected: >
            true
        stack: >
            http://localhost:7357/assets/test-support.js:3830:18
            http://localhost:7357/assets/tests.js:172:7
            runTest@http://localhost:7357/assets/test-support.js:2588:32
            run@http://localhost:7357/assets/test-support.js:2573:11
            http://localhost:7357/assets/test-support.js:2715:14
            process@http://localhost:7357/assets/test-support.js:2376:24
            begin@http://localhost:7357/assets/test-support.js:2358:9
            http://localhost:7357/assets/test-support.js:2418:9
        message: >
            helpers/module-for-acceptance.js should pass jscs.
            requireSpread: Illegal use of apply method. Use the spread operator instead at helpers/module-for-acceptance.js :
                 9 |
                10 |      if (options.beforeEach) {
                11 |        options.beforeEach.apply(this, arguments);
            -----------------------------------^
                12 |      }
                13 |    },
            requireSpread: Illegal use of apply method. Use the spread operator instead at helpers/module-for-acceptance.js :
                17 |
                18 |      if (options.afterEach) {
                19 |        options.afterEach.apply(this, arguments);
            ----------------------------------^
                20 |      }
                21 |    }
        Log: |
    ...
```

**Comment by brzpegasus** [comment]
That is new with the introduction of the `requireSpread` rule (it should also be the only JSCS error that shows up on a newly generated Ember CLI app).

**Comment by SmileyJames** [comment]
You're correct it is the only JSCS error, I was confused by the other fails.

**Comment by Ramblurr** [comment]
So, we're getting the requireSpread errors on ember cli generated files, what's the solution here?
