### ISSUE TITLE
Add binary for running from command line.

### ISSUE THREAD

**Issue by rwjblue** [dockyard/ember-suave#34]
I would like to be able to run `suave` or some other bin file from the command line, and get our default rule set.

This would build off the work done in https://github.com/dockyard/ember-suave/pull/15 (making the rule file generation/merging a separate utility function) and allow usage of our rule set in other scenarios than just Ember CLI.

**Comment by rwjblue** [comment]
This will also enable syntax checkers (like Emacs FlyCheck) to syntax check for us.

**Comment by alexlafroscia** [comment]
Is this required for `ember-suave` to be used with JSCS's `--fix` and editor integrations? Or is there any way to get those things with Suave in it's current state?

**Comment by rwjblue** [comment]
@alexlafroscia - Yes, the goal of this issue was for usage within my editor.  I assume that this would also allow `--fix`.

**Comment by swr** [comment]
Thoughts on what this would look like?

My initial brain dump:

- convert existing rule additions that suave makes to a jscs [plugin](https://github.com/jscs-dev/node-jscs/wiki/Plugin-API)
- switch suave to use said plugins via plugins config line in .jscs file in ember-suave
- expose functionality to others by:
  - making a wrapper that calls jscs with addon's jscs config - this makes a new interface that must be called by existing integrations
  - **OR**
  - include instructions on how to make a symlink from .jscsrc in your project root to node_modules/ember-suave/lib/jscsrc.json - I know it's hacky, but it would allow for these rules to "magically" start working in atom/vim/emacs/etc with standard jscs plugins

**Comment by hzoo** [comment]
We don't have good docs for it yet but you can make your own "preset" now. http://jscs.info/overview.html#preset

You need to use a `jscs.json` file instead of `.jscsrc`, and add that to `main` in the `package.json`. Then in your other repos you can do `"preset": "preset-ember-suave"` or something and run jscs normally. There is currently an issue with globally installed versions of jscs which should be fixed soon. The workaround is to do `"preset": "./node_modules/jscs-preset-ember-suave/.jscsrc"`. You can include other rules in the preset as well.

Ref https://github.com/jscs-dev/node-jscs/issues/863

Ex: https://github.com/behance/jscs-preset-behance/blob/master/package.json
https://github.com/wealthfront/javascript/blob/master/jscs/jscs.json

I also have an issue to port rules over to the main repo if anyone is interested https://github.com/jscs-dev/node-jscs/issues/1390

**Comment by raido** [comment]
I am interested in this too. I'd like Atom to use default preset + all the custom rules it by default provides. 

Or are there some hacky ways to get this going today?

**Comment by rwjblue** [comment]
I need to dig into @hzoo's suggestion above, but you can do this today by just adding your own .jscsrc file (then use the normal JSCS editor integrations).

Example from a project I recently started on: https://github.com/aptible/ember-json-schema/blob/master/.jscsrc

**Comment by raido** [comment]
Oh, yes. I can add these ember-suave custom rules directly from the node-modules. Thanks for the tip.

**Comment by hzoo** [comment]
@rwjblue I added some docs https://github.com/jscs-dev/node-jscs/wiki/Creating-a-Custom-Preset-or-Config. Let me know if I can help!

**Comment by rwjblue** [comment]
@hzoo - Awesome, thank you!  I'm digging into this now...

**Comment by rwjblue** [comment]
#70 should resolve this, also see https://github.com/aptible/ember-json-schema/pull/1 for the required changes in the project I linked before.

**Comment by raido** [comment]
Awesome!
