### ISSUE TITLE
Determine Versioning for New or Stricter Rules

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-suave#87]
I would like to land https://github.com/dockyard/ember-suave/pull/77, https://github.com/dockyard/ember-suave/pull/79, and https://github.com/dockyard/ember-suave/pull/80 but those all have the ability to add new test failures to a project that passes tests against ember-suave@1.2.3.

We need to decide a few things:

* What does SemVer mean for a style preset library like this?
* Does adding any new rules "break SemVer"?
* Does making an existing rule more strict "break SemVer"?
* Does that mean we have to increment majors for every new rule and use minor versions for bugfixes?

**Comment by brzpegasus** [comment]
I've had thoughts around this too.

We've been sticking to SemVer up until now, and I think people have come to expect/assume SemVer for pretty much any addons in the ember-cli ecosystem (that I know of). Even if `ember-suave` is "special" in it establishes a default set of style rules that may evolve over time rather than exposing a public API to be consumed (I suppose you could argue that the preset is the API), SemVer still has benefits in that it clearly informs users of the intent of a major/minor/patch version change. Otherwise, how else would we communicate that a version is safe to upgrade to and necessary for fixing a bug, or that a version upgrade would introduce breaking tests?

I'm particularly worried of current uses of `^1.x.x` or `~1.x.x` if we start changing the versioning model. The tests for any such projects could all pass one day, but break the next only because a fresh new `npm install` would pull down a version of the library that introduces a non-backwards compatible rule or stricter existing rule. So in that sense, yes, we would be breaking SemVer.

> Does that mean we have to increment majors for every new rule and use minor versions for bugfixes?

I'm afraid changing the preset in any way that causes previously passing tests to fail would require a major version bump. I still see reserving patch version bumps for bug fixes, and minor version bumps for other things, such as when we made all the rules' error messages verbose by default.

If we wanted to be a bit more conservative on how often to release a new major version, we could still add the breaking rules but leave the preset alone, bump the minor version, then only release a preset and major version when we have a handful of breaking changes to bundle up.

I welcome other suggestions, of course!

**Comment by rwjblue** [comment]
>  I'm particularly worried of current uses of ^1.x.x or ~1.x.x if we start changing the versioning model. The tests for any such projects could all pass one day, but break the next only because a fresh new npm install would pull down a version of the library that introduces a non-backwards compatible rule or stricter existing rule.

To some extent this problem exists already.  If a JSCS update fixes a previously silent parsing error and now a file is actually being linted instead of ignored, that update has broken their test suite.  Note: I am not really saying we can or should do anything about this (it was clearly a bugfix), but it is a fact of life.

> I'm afraid changing the preset in any way that causes previously passing tests to fail would require a major version bump.

OK, so adding or modifying any rule that isn't strictly a bugfix means we do a major version bump. Is that an accurate summary?

> If we wanted to be a bit more conservative on how often to release a new major version, we could still add the breaking rules but leave the preset alone, bump the minor version, then only release a preset and major version when we have a handful of breaking changes to bundle up.

I'm not a giant fan of this.  IMHO, the whole point of ember-suave is that it is opinionated and easy to use. If we have changed our opinions and think there is a better way to do something, then we should just bump versions. I think that batching up changes for a future major version bump will cause more pain than just releasing when we have things ready.

**Comment by rwjblue** [comment]
A slight tweak of the language above in an attempt to circle in on something we can put into the README regarding versioning and versions:

* Bug fixes will continue to be released as minor or patch version bumps.  In some limited cases a bugfix might cause a previously ignored file or section to be parsed and trigger a failed test, but this is fairly unlikely.
* Changing the preset in any way that causes previously passing tests to fail would require a major version bump.

@brzpegasus - What do you think?

**Comment by brzpegasus** [comment]
That sounds good to me. And yes, you're right about this:

> To some extent this problem exists already.

I was just thinking that while adding #88 :stuck_out_tongue:. There was a fix to the `disallowTrailingComma` rule in JSCS that would have caused previously passing tests (the ones with trailing commas in object/array destructuring) to all of a sudden fail.

**Comment by rwjblue** [comment]
Hehe, exactly.  I think the best we can do is fix things that are clearly bugs under a minor or patch release, and when we intentionally change strictness (add new rules, change preset values in our `jscsrc.json`, etc) we bump major versions.  

It feels weird to release a bunch of major versions, but I think that gives as much stability to consumers as is possible.

**Comment by rwjblue** [comment]
FWIW - Looks like we ended up being pretty much aligned with JSCS itself.  See their statement on SemVer: http://jscs.info/overview#versioning-semver.

**Comment by brzpegasus** [comment]
Nice! Good to see that. =)
